name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean npm cache
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install --legacy-peer-deps --no-package-lock
          echo "Dependencies installed successfully"

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Check formatting
        run: npm run format --check

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit package-lock.json
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in files"
            git add .
            git commit -m "chore: update dependencies [skip ci]"
            git push
          else
            echo "No changes detected"
          fi 