name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Check formatting
        run: npm run format --check

      - name: Commit package-lock.json if changed
        run: |
          if [[ -n "$(git status --porcelain package-lock.json)" ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add package-lock.json
            git commit -m "chore: update package-lock.json"
            git push
          fi 