name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '18'
  NPM_CONFIG_LEGACY_PEER_DEPS: true
  NPM_CONFIG_PACKAGE_LOCK: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean environment
        run: |
          echo "Cleaning npm cache and removing old files..."
          npm cache clean --force
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed successfully"

      - name: Setup Prisma
        run: |
          echo "Generating Prisma Client..."
          npx prisma generate
          echo "Prisma Client generated successfully"

      - name: Build and test
        run: |
          echo "Running lint..."
          npm run lint
          echo "Running build..."
          npm run build
          echo "Running tests..."
          npm run test --if-present

      - name: Check formatting
        run: |
          echo "Checking code formatting..."
          npm run format --check

      - name: Commit changes
        if: github.ref == 'refs/heads/main'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected, committing..."
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "chore: update dependencies [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi 